### PR TITLE
Fix LTO detection for cross-native builds

### LINKED ISSUE #36: Cannot infer architecture for objects files compiled with LTO on Apple Silicon / M1 / osx-arm64
Feel free to point me to a repo where this ticket is more appropriate.

I'm facing an issue which connects to the python3.8 builds since they were compiled with LTO options and the shipped toolchain with, e.g. `c-compilers` is not capable of reading the created object files.

minimal example

```
conda create -n lto-python-failure python=3.8 c-compiler
conda activate lto-python-failure
```

Use `a.h` and `a.c` from https://llvm.org/docs/LinkTimeOptimization.html#example-of-link-time-optimization

```c
--- a.h ---
extern int foo1(void);
extern void foo2(void);
extern void foo4(void);

--- a.c ---
#include "a.h"

static signed int i = 0;

void foo2(void) {
  i = -1;
}

static int foo3() {
  foo4();
  return 10;
}

int foo1(void) {
  int data = 0;

  if (i < 0)
    data = foo3();

  data = data + 42;
  return data;
}
```

```
clang -flto -c a.c -o a.o
lipo -info a.o
> fatal error: lipo: can't figure out the architecture type of: a.o
```

Using the OSX shipped toolchain, this works without issues

```
/Library/Developer/CommandLineTools/usr/bin/lipo -info a.o
input file a.o is not a fat file
Non-fat file: a.o is architecture: arm64
```

The problem and connection with the py3.8 builds is introduced since the py3.8 builds are using LTO which sets the `PY_CFLAGS` (see ` python -m sysconfig`) which are used by Cython and cannot be removed / overridden afaik (you can append flags using environment C_FLAGS but I am not aware of a method to remove a flag, i.e. how to remove `-flto`)

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/fjetter/mambaforge/envs/lto-python-failure:
#
# Name                    Version                   Build  Channel
c-compiler                1.1.3                h27ca646_0    conda-forge
ca-certificates           2020.12.5            h4653dfc_0    conda-forge
cctools                   949.0.1             ha9384d2_20    conda-forge
cctools_osx-arm64         949.0.1             h1c8944f_20    conda-forge
certifi                   2020.12.5        py38h10201cd_1    conda-forge
clang                     11.1.0               hce30654_0    conda-forge
clang-11                  11.1.0          default_h87665d4_0    conda-forge
clang_osx-arm64           11.1.0               h54d7cd3_0    conda-forge
clangxx                   11.1.0          default_hbe4449c_0    conda-forge
compiler-rt               11.1.0               h7d99272_0    conda-forge
compiler-rt_osx-arm64     11.1.0               h103ad0d_0    conda-forge
ld64                      530                 h08716b2_20    conda-forge
ld64_osx-arm64            530                 h8a2aa15_20    conda-forge
ldid                      2.1.2                h34db0f2_2    conda-forge
libclang-cpp11.1          11.1.0          default_h87665d4_0    conda-forge
libcxx                    11.1.0               h168391b_0    conda-forge
libffi                    3.3                  h9f76cd9_2    conda-forge
libllvm11                 11.1.0               h93073aa_1    conda-forge
llvm-openmp               11.1.0               hb3022d6_0    conda-forge
llvm-tools                11.1.0               h93073aa_1    conda-forge
ncurses                   6.2                  h9aa5885_4    conda-forge
openssl                   1.1.1k               h27ca646_0    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
python                    3.8.8           h12cc5a1_0_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.1                  hfbdcbf2_0    conda-forge
setuptools                49.6.0           py38h10201cd_3    conda-forge
sqlite                    3.35.3               h6d56c25_0    conda-forge
tapi                      1100.0.11            he4954df_0    conda-forge
tk                        8.6.10               hf7e6567_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
zlib                      1.2.11            h31e879b_1009    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : lto-python-failure
    active env location : /Users/fjetter/mambaforge/envs/lto-python-failure
            shell level : 4
       user config file : /Users/fjetter/.condarc
 populated config files : /Users/fjetter/mambaforge/.condarc
                          /Users/fjetter/.condarc
          conda version : 4.10.0
    conda-build version : not installed
         python version : 3.9.2.final.0
       virtual packages : __osx=11.2.3=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/fjetter/mambaforge  (writable)
      conda av data dir : /Users/fjetter/mambaforge/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/fjetter/mambaforge/pkgs
                          /Users/fjetter/.conda/pkgs
       envs directories : /Users/fjetter/mambaforge/envs
                          /Users/fjetter/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.10.0 requests/2.25.1 CPython/3.9.2 Darwin/20.3.0 OSX/11.2.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

cc @xhochy

### PR DESCRIPTION
**Pull request by isuruf**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes https://github.com/conda-forge/cctools-and-ld64-feedstock/issues/36

### CODE REVIEW

File: recipe/build.sh [hunk 1]
```diff
@@ -29,7 +29,12 @@ popd
 if [[ "$CONDA_BUILD_CROSS_COMPILATION" == "1" ]]; then
   # llvm-config from host env is tried by cctools-port
   # Move the build prefix one to host prefix
-  mv $BUILD_PREFIX/bin/llvm-config $PREFIX/bin/llvm-config
+  rm $PREFIX/bin/llvm-config
```
Comment (katietz) [inline recipe/build.sh:32]: I know that it shouldn't be normally necessary, but I think specifying here a '-f' is more sane, as even if that file doesn't exist at that place, we want to move it in from other place, isn't it?
Otherwise changes are looking good to me.

Comment (isuruf) [reply recipe/build.sh:32]: Yes, I'll clean it up. The INSTALL_NAME_TOOL hack is also not needed because `llvm-config` no longer links with `libLLVM.dylib` because of https://github.com/conda-forge/llvmdev-feedstock/commit/07506fbe731f9e716a4892d16898fba4acd40062
